# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install Terraform
    init: brew tap hashicorp/tap # runs during prebuild
    command: brew install hashicorp/tap/terraform
