tasks:
  - name: Install Terraform
    init: brew tap hashicorp/tap # runs during prebuild
    command: brew install hashicorp/tap/terraform
    openMode: split-left
  - name: Initalise Terraform
    init: terraform init
    command: terraform plan
  - name: Free terminal
    command: echo "For anything you want!"
    openMode: split-right
    env:
      MY_SECRET_KEY: "define these in Gitpod Dashboard, don't commit to .gitpod.yml file :)"
      MY_ACCESS_KEY: "define these in Gitpod Dashboard, don't commit to .gitpod.yml file :)"
vscode:
  extensions:
    - hashicorp.terraform
