# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install Terraform
    init: brew tap hashicorp/tap && brew install hashicorp/tap/terraform # runs during prebuild
    command: terraform version
